FROM node:20.19.6-alpine

WORKDIR /app

# Needed for bcrypt
RUN apk add --no-cache python3 make g++

# Install deps first (better cache)
COPY package*.json ./


RUN npm ci

# Nodemon needs file system events
# this one makes sure nodemon uses polls, which is necessary with alpine
ENV CHOKIDAR_USEPOLLING=true

COPY ./tools/dev-start.sh /tools/dev-start.sh

RUN chmod 700 /tools/dev-start.sh

EXPOSE 3000

ENTRYPOINT ["/tools/dev-start.sh"]
