FROM node:20.19.6-alpine

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL


WORKDIR /app

# Only dependencies are baked into the image
COPY front-end/package*.json ./
RUN npm ci

# EMILIE added for hot reloaded on windows
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=100

EXPOSE 5173

COPY ./tools/dev-start.sh /tools/dev-start.sh

RUN chmod 700 /tools/dev-start.sh

ENTRYPOINT ["/tools/dev-start.sh"]

# Source code comes from bind mount
